config/routes.rb
Rails.application.routes.draw do

  root 'billboards#index'

  resources :billboards do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update]

  def index
    @billboards = Billboard.all
  end

  def show
    
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @sub.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit  
    end
  end

  def destroy
    Billboard.find(params[:id]).destroy
    redirect_to billboards_path
  end

  private

  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboards).permit(:rank, :artist, :title, :genre)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_billboard
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    # @topics = Topic.all
              # parent.model_name(s)
    @songs = @billboard.songs
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    # @topic = Topic.new
    @song = @billboard.songs.new
    render partial: 'form'
  end

  def create
    # @topic = Topic.new(topic_params)
    @song = @billboard.songs.new(song_params)
    if @song.save
      redirect_to [@billboard, @song]
    else
      render :new
    end
  end

  def edit
    # @topic = Topic.find(params[:id])
    render partial: 'form'
  end

  def update
    # @topic = Topic.find(params[:id])
    if @song.update(song_params)
          redirect_to [@billboard, @song]
        else
          render :edit
        end
  end

def destroy
  # @topic.find(params[:id]).destroy
  @song.destroy
  redirect_to billboard_song_path(@billboard)
end


  private
    def song_params
          params.require(:song).permit(:title, :artist, :runtime, :top_100)
          # check scheme if you do'nt know 
        end

        def set_billboard
          @billboard = Billboard.find(params[:billboard_id])
        end

        def set_song
          @song = Song.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>TS TOP 100</h1>

<%= link_to 'Add A Song', new_billboard_path %>


<ul>
  <% @billboards.each do |song|%>
    <li><%= link_to song.name, song %></li>
  <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsTop100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>